name: React App Deployment # name of the workflow

on:
  push:
    branches:
      - master # branch name

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: CI=false && npm run build

      # git config and url
      - name: Config Github and origin url
        run: |
          git config --global user.email '${{ secrets.EMAIL }}'
          git config --global user.name '${{ secrets.USERNAME }}'
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/${{ secrets.ORIGIN_URL }}

      # deploy the react app to github pages
      - name: Deploy
        run: CI=false && npm run deploy